version: '3'
services:
  # Cassandra for storing data
  cassandra:
    image: cassandra:latest
    container_name: project_database
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  # Kafka for message streaming
  kafka:
    image: bitnami/kafka:latest
    container_name: project_messagebroker
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  cassandra_data:
  kafka_data: